# Generated by Django 4.1 on 2023-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_tasktype_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="duties",
            field=models.TextField(blank=True),
        ),
    ]
