# Generated by Django 4.1 on 2023-05-15 13:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("task_manager", "0005_remove_project_team_team_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
