# Generated by Django 4.1 on 2023-05-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0008_alter_worker_position_alter_worker_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8
            ),
        ),
    ]
